config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  

  get 'main/index'
  root 'main#index'
  resources :reports
  resources :operations
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :operations

  validates :name, presence: true, uniqueness: true
  validates :description, allow_nil: false, presence: true, length: { minimum: 1 }  
end

app/models/operation.rb
class Operation < ApplicationRecord
  paginates_per 2
  belongs_to :category
  enum otype: { expenses: 0, income: 1, loan: 2 }
#enum :type, [ :spending, :income, :loan ]
  
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :odate, presence: true, length: { minimum: 1 }
  validates :description, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations or /operations.json
  def index
    @operations = Operation.page(params[:page])
    #@operations = Operation.all
    console
  end

  # GET /operations/1 or /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
    @categories = Category.all()
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:amount, :odate, :description, :category_id, :otype)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
  end

  def report_by_category
  end

  def report_by_dates
    operations_data = Operation.all.map { |op| [op.odate.to_s, op.exchange_operation] }
    @dates = operations_odate.map { |e| e[0] }
    @amounts = rates_data.map { |e| e[1] }

    rates_data = Rate.all.map { |r| [r.rdate.to_s, r.exchange_rate] }
    @dates = rates_data.map { |e| e[0] }
    @rates = rates_data.map { |e| e[1] }  :amount, :odate,
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    render :index
    reports_date = Operation.all.map {
      |p| [ p.odate.to_s, p.amount ]
    }
    @odates = reports_date.map { |e| e[0] }
    @amounts = reports_date.map { |e| e[1] }
  end

  def report_by_category
  end

  def report_by_dates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
<p>
<div class="col-2">
<div>
<%= form.submit "Submit", class:"btn btn-success" %>
</div>
</div>
</p>
<% end %>

app/views/categories/edit.html.erb
<div class="container-fluid">
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>
<p>
<div>
  <%= link_to "Show this category", @category, class:"btn btn-warning" %>
  <%= link_to "Back to categories", categories_path, class:"btn btn-primary" %>
</div>
</p>
</div>

app/views/categories/index.html.erb
<div class="container-fluid">
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category, class:"btn btn-primary" %>
    </p>
  <% end %>
</div>

<p>
  <%= link_to "New category", new_category_path, class:"btn btn-success" %>
</p>
</div>

app/views/categories/new.html.erb
<div class="container-fluid">
  <h1>New category</h1>

  <%= render "form", category: @category %>

  <br>
  <p>
  <div>
    <%= link_to "Back to categories", categories_path, class:"btn btn-primary" %>
  </div>
  </p>
</div>

app/views/categories/show.html.erb
<div class="container-fluid">
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category), class:"btn btn-warning" %>
  <%= link_to "Back to categories", categories_path, class:"btn btn-primary" %>
<p> 
  <%= button_to "Destroy this category", @category, method: :delete, class:"btn btn-danger" %>
</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfinance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
   
   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/header" %>
  <%= yield %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/operations/_form.html.erb
<%= form_with(model: operation) do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row g-3 align-items-left">
    <div class="col-2 text">
  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>
  </div>
  </div>

  <div class="row g-3 align-items-center">
    <div class="col-2 text">
  <div>
    <%= form.label :odate, style: "display: block" %>
    <%= form.datetime_field :odate %>
  </div>
  </div>
  </div>  


  <div class="row g-3 align-items-left">
    <div class="col-2 text">
  <div>
  <%= form.label :otype, style: "display: block" %>
  <%= form.select :otype, Operation.otypes.keys %>
  </div> 
  </div>
  </div>  

<div class="row g-3 align-items-left">
    <div class="col-2 text">
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  </div>
  </div>    

  <div class="row g-3 align-items-left">
    <div class="col-2 text">
      <label for="operation_category_id" class="form-label">Category</label>

      <select
          name="operation[category_id]"
          id="operation_category_id"
          class="form-select"
      >
          <%= Category.all.each do |c| %>
          <option value=<%= c.id %>>
            <%= c.name %>
          </option>
          <% end %>
      </select>
    </div>
  </div>
 <p>
  <div class="col-2">
<div>
<%= form.submit "Submit", class:"btn btn-success" %>
</div>
</div>
</p>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <p>
    <strong>Amount:</strong>
    <%= operation.amount %>
  </p>

  <p>
    <strong>Odate:</strong>
    <%= operation.odate %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= operation.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= operation.category_id %>
  </p>

</div>

app/views/operations/edit.html.erb
<div class="container-fluid">
  <h1>Editing operation</h1>

  <%= render "form", operation: @operation %>

  <br>
  <p>
  <div>
    <%= link_to "Show this operation", @operation, class:"btn btn-warning" %>
    <%= link_to "Back to operations", operations_path, class:"btn btn-primary" %>
  </div>
  </p>
</div>

app/views/operations/index.html.erb
<div class="container-fluid">
  <p style="color: green"><%= notice %></p>

  <h1>Operations</h1>

  <div id="operations">
    <% @operations.each do |operation| %>
    <%= render operation %>
      <p>
        <%= link_to "Show this operation", operation, class:"btn btn-primary" %>
      </p>
    <% end %>
  </div>
  <%= paginate @operations %>

  <p>
    <%= link_to "New operation", new_operation_path, class:"btn btn-success" %>
  </p>
</div>

app/views/operations/new.html.erb
<div class="container-fluid">
  <h1>New operation</h1>

  <%= render "form", operation: @operation %>

  <p>
    <div>
      <%= link_to "Back to operations", operations_path, class:"btn btn-primary" %>
    </div>
  </p>
</div>

app/views/operations/show.html.erb
<div class="container-fluid">
  <p style="color: green"><%= notice %></p>

  <%= render @operation %>

  <div>
    <%= link_to "Edit this operation", edit_operation_path(@operation), class:"btn btn-warning" %> 
    <%= link_to "Back to operations", operations_path, class:"btn btn-success" %>
    <p>
      <div class="col-2">
        <%= button_to "Destroy this operation", @operation, method: :delete, class:"btn btn-danger" %>
      </div>
    </p> 
  </div>
</div>

app/views/report/report_by_dates.html.erb
<h1>Report#report_by_dates</h1>
<p>Find me in app/views/report/report_by_dates.html.erb</p>

app/views/reports/index.html.erb
<div class="container-fluid">
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

<!-- Input start_date -->
<div class="row g-3 align-items-center">
    <div class="col-2 text">
  <div>
    <%= form.label :odate, style: "display: block" %>
    <%= form.datetime_field :odate %>
  </div>
  </div>
  </div>  
  <!-- Input end_date -->
  <div class="row g-3 align-items-center">
    <div class="col-2 text">
  <div>
    <%= form.label :odate, style: "display: block" %>
    <%= form.datetime_field :odate %>
  </div>
  </div>
  </div>

  <!-- Input Category -->
 div class="row g-3 align-items-left">
    <div class="col-2 text">
      <label for="operation_category_id" class="form-label">Category</label>

      <select
          name="operation[category_id]"
          id="operation_category_id"
          class="form-select"
      >
          <%= Category.all.each do |c| %>
          <option value=<%= c.id %>>
            <%= c.name %>
          </option>
          <% end %>
      </select>
    </div>
  </div>

  <!-- Input Type -->
  div class="row g-3 align-items-left">
    <div class="col-2 text">
  <div>
  <%= form.label :otype, style: "display: block" %>
  <%= form.select :otype, Operation.otypes.keys %>
  </div> 
  </div>
  </div>  

  <p>
  <div>
  <div class="col-2">
  <button type="reset" class="btn btn-primary bg-gradient mx-3">
      Очистити
  </button>
    <%= link_to_ "Report by dates", report_by_dates_path, class:"btn btn-success" %>
    <%= link_to "Report by category", report_by_category_path, class:"btn btn-primary" %>
  </div>
  </div>
  </p>


</div>  

app/views/reports/report_by_category.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<h1>Report#report_by_category</h1>
<p>Find me in app/views/reports/report_by_category.html.erb</p>

<canvas id="myChart" width="600" height="400"></canvas>
<script>
  const ctx = document.getElementById('myChart').getContext('2d');
  const data = {
  labels: <%= raw @odates %>,
  datasets: [{
    label: 'Exchange Rate',
    data: <%= @amounts %>,
    fill: false,
    borderColor: 'rgb(75, 192, 192)',
    tension: 0.1
  }]
};

const config = {
  type: 'line',
  data: data,
  options: {
    responsive: false
  }
};

const myChart = new Chart(ctx, config);
</script>

<script type='text/javascript'>
  (function(){
    if(!sessionStorage.getItem('firstLoad')){
      sessionStorage['firstLoad'] = true;
      window.location.reload();
    }else{
      sessionStorage.removeItem('firstLoad');
  }})();
</script> 

app/views/reports/report_by_dates.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<h1>Report</h1>
<canvas id="myChart" width="600" height="400"></canvas>
<script>
  const ctx = document.getElementById('myChart').getContext('2d');
  const data = {
  labels: <%= raw @odates %>,
  datasets: [{
    label: 'Exchange Rate',
    data: <%= @amounts %>,
    fill: false,
    borderColor: 'rgb(75, 192, 192)',
    tension: 0.1
  }]
};

const config = {
  type: 'line',
  data: data,
  options: {
    responsive: false
  }
};

const myChart = new Chart(ctx, config);

<script type='text/javascript'>
  (function(){
    if(!sessionStorage.getItem('firstLoad')){
      sessionStorage['firstLoad'] = true;
      window.location.reload();
    }else{
      sessionStorage.removeItem('firstLoad');
  }})();
</script>     
</script>

<h1>Reports#report_by_dates</h1>
<p>Find me in app/views/reports/report_by_dates.html.erb</p>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->

    
    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
        eum harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>
    
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/operations#">Operation</a></li>
            <li><a class="dropdown-item" href="/categories#">Categories</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>

app/views/shared/report_graph.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<h1>Rates</h1>
<canvas id="myChart" width="600" height="400"></canvas>
<script>
  const ctx = document.getElementById('myChart').getContext('2d');
  const data = {
  labels: <%= raw @dates %>,
  datasets: [{
    label: 'Exchange Rate',
    data: <%= @operations %>,
    fill: false,
    borderColor: 'rgb(75, 192, 192)',
    tension: 0.1
  }]
};

const config = {
  type: 'line',
  data: data,
  options: {
    responsive: false
  }
};

const myChart = new Chart(ctx, config);

<script type='text/javascript'>
  (function(){
    if(!sessionStorage.getItem('firstLoad')){
      sessionStorage['firstLoad'] = true;
      window.location.reload();
    }else{
      sessionStorage.removeItem('firstLoad');
  }})();
</script>     
</script>